id: P005620
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18832
  title: དམངས་རྩོད་གཏུག་བཤེར་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    285316c74b344522b955cccb0fae61b1:
      image_group_id: I8LS18834
      title: ''
      volume_number: 1
      total_pages: 180
      base_file: v001.txt
